version: '3.3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my_network # Utilizaremos a mesma rede personalizada "my_network"


networks:
  my_network: # Definição da rede personalizada